version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "127.0.0.1:7687:7687" # DELETE ME
      - "127.0.0.1:7474:7474"
    healthcheck:
      test: "wget http://localhost:7474 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
#    volumes:
#      - neo4j_data:/data

  app:
    build: .
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      neo4j:
        condition: service_healthy
#volumes:
#  neo4j_data: