version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - app-network
    healthcheck:
      test: "wget http://localhost:7474 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - neo4j_data:/data

  app:
    build: .
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    networks:
      - app-network
    depends_on:
      neo4j:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app-network
    depends_on:
      - app

volumes:
  neo4j_data:

networks:
  app-network:
    driver: bridge